Date::DATE_FORMATS[:default] = "%Y年%m月%d日"
Date::DATE_FORMATS[:date] = "%y/%m/%d"
Time::DATE_FORMATS[:default] = "%Y年%m月%d日 %H時%M分%S秒"
Time::DATE_FORMATS[:datetime] = "%Y/%m/%d %H:%M:%S"
Time::DATE_FORMATS[:date] = "%y/%m/%d"
Time::DATE_FORMATS[:time] = "%H:%M:%S"
